<?php

require_once dirname(__FILE__) . '../../classes/ValidationHandler.php';
require_once dirname(__FILE__) . '../../classes/UserHandler.php';

//Will hold all errors generated by the validation methods
$errors = array();
$username = $_POST["Username"];
$email = $_POST["Email"];
$password1 = $_POST["Password1"];
$password2 = $_POST["Password2"];
$captchaCode = $_POST['captcha_code'];

$valHandler = new ValidationHandler();
$valHandler->validateCaptcha($captchaCode, $errors);
$valHandler->validateUsername($username, $errors);
$valHandler->validateEmail($email, $errors);
$valHandler->validatePasswords($password1, $password2, $errors);

if (count($errors) > 0)
{
    //If there were any errors, user is informed and no action is taken
    echo '<h3>The following errors occured whilst creating your account!</h3>';
    foreach ($errors as $error)
    {
        echo "&nbsp;&nbsp;- " . $error . "<br/>";
    }
    echo '<br/>'
    . '<button class="ui fluid primary button"type="submit" onclick="window.location = \'../registrationPage.php\'";>Back to registration page.</button>';
}
else
{
    //If there were no errors, the account can be created
    $userHandler = new UserHandler();
    $userHandler->createUser($username, $email, $password1);
    echo 'Your account was successfully created';
    echo '<br/>'
    . '<button class="ui fluid primary button"type="submit" onclick="window.location = \'../loginPage.php\'";>Back to login page.</button>';
}
?>
